;21:44:30 28/10

(define (problem unpack-3blocks)
   (:domain blocks)

   (:objects
          region1__-1__-1 - location
          region1__-1__-2 - location
          region1__-1__-3 - location
          region1__-1__-4 - location
          region1__-1__-5 - location
          region1__-1__0 - location
          region1__-1__1 - location
          region1__-1__2 - location
          region1__-1__3 - location
          region1__-1__4 - location
          region1__-1__5 - location
          region1__-2__-1 - location
          region1__-2__-2 - location
          region1__-2__-3 - location
          region1__-2__-4 - location
          region1__-2__-5 - location
          region1__-2__0 - location
          region1__-2__1 - location
          region1__-2__2 - location
          region1__-2__3 - location
          region1__-2__4 - location
          region1__-2__5 - location
          region1__-3__-1 - location
          region1__-3__-2 - location
          region1__-3__-3 - location
          region1__-3__-4 - location
          region1__-3__-5 - location
          region1__-3__0 - location
          region1__-3__1 - location
          region1__-3__2 - location
          region1__-3__3 - location
          region1__-3__4 - location
          region1__-3__5 - location
          region1__-4__-1 - location
          region1__-4__-2 - location
          region1__-4__-3 - location
          region1__-4__-4 - location
          region1__-4__-5 - location
          region1__-4__0 - location
          region1__-4__1 - location
          region1__-4__2 - location
          region1__-4__3 - location
          region1__-4__4 - location
          region1__-4__5 - location
          region1__-5__-1 - location
          region1__-5__-2 - location
          region1__-5__-3 - location
          region1__-5__-4 - location
          region1__-5__-5 - location
          region1__-5__0 - location
          region1__-5__1 - location
          region1__-5__2 - location
          region1__-5__3 - location
          region1__-5__4 - location
          region1__-5__5 - location
          region1__0__-1 - location
          region1__0__-2 - location
          region1__0__-3 - location
          region1__0__-4 - location
          region1__0__-5 - location
          region1__0__0 - location
          region1__0__1 - location
          region1__0__2 - location
          region1__0__3 - location
          region1__0__4 - location
          region1__0__5 - location
          region1__1__-1 - location
          region1__1__-2 - location
          region1__1__-3 - location
          region1__1__-4 - location
          region1__1__-5 - location
          region1__1__0 - location
          region1__1__1 - location
          region1__1__2 - location
          region1__1__3 - location
          region1__1__4 - location
          region1__1__5 - location
          region1__2__-1 - location
          region1__2__-2 - location
          region1__2__-3 - location
          region1__2__-4 - location
          region1__2__-5 - location
          region1__2__0 - location
          region1__2__1 - location
          region1__2__2 - location
          region1__2__3 - location
          region1__2__4 - location
          region1__2__5 - location
          region1__3__-1 - location
          region1__3__-2 - location
          region1__3__-3 - location
          region1__3__-4 - location
          region1__3__-5 - location
          region1__3__0 - location
          region1__3__1 - location
          region1__3__2 - location
          region1__3__3 - location
          region1__3__4 - location
          region1__3__5 - location
          region1__4__-1 - location
          region1__4__-2 - location
          region1__4__-3 - location
          region1__4__-4 - location
          region1__4__-5 - location
          region1__4__0 - location
          region1__4__1 - location
          region1__4__2 - location
          region1__4__3 - location
          region1__4__4 - location
          region1__4__5 - location
          region1__5__-1 - location
          region1__5__-2 - location
          region1__5__-3 - location
          region1__5__-4 - location
          region1__5__-5 - location
          region1__5__0 - location
          region1__5__1 - location
          region1__5__2 - location
          region1__5__3 - location
          region1__5__4 - location
          region1__5__5 - location
          region2__-1__-1 - location
          region2__-1__-2 - location
          region2__-1__-3 - location
          region2__-1__-4 - location
          region2__-1__-5 - location
          region2__-1__-6 - location
          region2__-1__-7 - location
          region2__-1__0 - location
          region2__-1__1 - location
          region2__-1__2 - location
          region2__-1__3 - location
          region2__-1__4 - location
          region2__-1__5 - location
          region2__-1__6 - location
          region2__-1__7 - location
          region2__-2__-1 - location
          region2__-2__-2 - location
          region2__-2__-3 - location
          region2__-2__-4 - location
          region2__-2__-5 - location
          region2__-2__-6 - location
          region2__-2__-7 - location
          region2__-2__0 - location
          region2__-2__1 - location
          region2__-2__2 - location
          region2__-2__3 - location
          region2__-2__4 - location
          region2__-2__5 - location
          region2__-2__6 - location
          region2__-2__7 - location
          region2__-3__-1 - location
          region2__-3__-2 - location
          region2__-3__-3 - location
          region2__-3__-4 - location
          region2__-3__-5 - location
          region2__-3__-6 - location
          region2__-3__-7 - location
          region2__-3__0 - location
          region2__-3__1 - location
          region2__-3__2 - location
          region2__-3__3 - location
          region2__-3__4 - location
          region2__-3__5 - location
          region2__-3__6 - location
          region2__-3__7 - location
          region2__-4__-1 - location
          region2__-4__-2 - location
          region2__-4__-3 - location
          region2__-4__-4 - location
          region2__-4__-5 - location
          region2__-4__-6 - location
          region2__-4__-7 - location
          region2__-4__0 - location
          region2__-4__1 - location
          region2__-4__2 - location
          region2__-4__3 - location
          region2__-4__4 - location
          region2__-4__5 - location
          region2__-4__6 - location
          region2__-4__7 - location
          region2__-5__-1 - location
          region2__-5__-2 - location
          region2__-5__-3 - location
          region2__-5__-4 - location
          region2__-5__-5 - location
          region2__-5__-6 - location
          region2__-5__-7 - location
          region2__-5__0 - location
          region2__-5__1 - location
          region2__-5__2 - location
          region2__-5__3 - location
          region2__-5__4 - location
          region2__-5__5 - location
          region2__-5__6 - location
          region2__-5__7 - location
          region2__-6__-1 - location
          region2__-6__-2 - location
          region2__-6__-3 - location
          region2__-6__-4 - location
          region2__-6__-5 - location
          region2__-6__-6 - location
          region2__-6__-7 - location
          region2__-6__0 - location
          region2__-6__1 - location
          region2__-6__2 - location
          region2__-6__3 - location
          region2__-6__4 - location
          region2__-6__5 - location
          region2__-6__6 - location
          region2__-6__7 - location
          region2__-7__-1 - location
          region2__-7__-2 - location
          region2__-7__-3 - location
          region2__-7__-4 - location
          region2__-7__-5 - location
          region2__-7__-6 - location
          region2__-7__-7 - location
          region2__-7__0 - location
          region2__-7__1 - location
          region2__-7__2 - location
          region2__-7__3 - location
          region2__-7__4 - location
          region2__-7__5 - location
          region2__-7__6 - location
          region2__-7__7 - location
          region2__0__-1 - location
          region2__0__-2 - location
          region2__0__-3 - location
          region2__0__-4 - location
          region2__0__-5 - location
          region2__0__-6 - location
          region2__0__-7 - location
          region2__0__0 - location
          region2__0__1 - location
          region2__0__2 - location
          region2__0__3 - location
          region2__0__4 - location
          region2__0__5 - location
          region2__0__6 - location
          region2__0__7 - location
          region2__1__-1 - location
          region2__1__-2 - location
          region2__1__-3 - location
          region2__1__-4 - location
          region2__1__-5 - location
          region2__1__-6 - location
          region2__1__-7 - location
          region2__1__0 - location
          region2__1__1 - location
          region2__1__2 - location
          region2__1__3 - location
          region2__1__4 - location
          region2__1__5 - location
          region2__1__6 - location
          region2__1__7 - location
          region2__2__-1 - location
          region2__2__-2 - location
          region2__2__-3 - location
          region2__2__-4 - location
          region2__2__-5 - location
          region2__2__-6 - location
          region2__2__-7 - location
          region2__2__0 - location
          region2__2__1 - location
          region2__2__2 - location
          region2__2__3 - location
          region2__2__4 - location
          region2__2__5 - location
          region2__2__6 - location
          region2__2__7 - location
          region2__3__-1 - location
          region2__3__-2 - location
          region2__3__-3 - location
          region2__3__-4 - location
          region2__3__-5 - location
          region2__3__-6 - location
          region2__3__-7 - location
          region2__3__0 - location
          region2__3__1 - location
          region2__3__2 - location
          region2__3__3 - location
          region2__3__4 - location
          region2__3__5 - location
          region2__3__6 - location
          region2__3__7 - location
          region2__4__-1 - location
          region2__4__-2 - location
          region2__4__-3 - location
          region2__4__-4 - location
          region2__4__-5 - location
          region2__4__-6 - location
          region2__4__-7 - location
          region2__4__0 - location
          region2__4__1 - location
          region2__4__2 - location
          region2__4__3 - location
          region2__4__4 - location
          region2__4__5 - location
          region2__4__6 - location
          region2__4__7 - location
          region2__5__-1 - location
          region2__5__-2 - location
          region2__5__-3 - location
          region2__5__-4 - location
          region2__5__-5 - location
          region2__5__-6 - location
          region2__5__-7 - location
          region2__5__0 - location
          region2__5__1 - location
          region2__5__2 - location
          region2__5__3 - location
          region2__5__4 - location
          region2__5__5 - location
          region2__5__6 - location
          region2__5__7 - location
          region2__6__-1 - location
          region2__6__-2 - location
          region2__6__-3 - location
          region2__6__-4 - location
          region2__6__-5 - location
          region2__6__-6 - location
          region2__6__-7 - location
          region2__6__0 - location
          region2__6__1 - location
          region2__6__2 - location
          region2__6__3 - location
          region2__6__4 - location
          region2__6__5 - location
          region2__6__6 - location
          region2__6__7 - location
          region2__7__-1 - location
          region2__7__-2 - location
          region2__7__-3 - location
          region2__7__-4 - location
          region2__7__-5 - location
          region2__7__-6 - location
          region2__7__-7 - location
          region2__7__0 - location
          region2__7__1 - location
          region2__7__2 - location
          region2__7__3 - location
          region2__7__4 - location
          region2__7__5 - location
          region2__7__6 - location
          region2__7__7 - location
          c1 - block
          c2 - block
          c3 - block
   )

   (:init
          (handempty)
          (ontable c1 region1__1__0)
          (ontable c2 region1__-1__0)
          (ontable c3 region1__0__-2)
   )

   (:goal
   (and
        (handempty)
        (ontable c1 region2__0__0)
   ))

)
